name: Format and Lint and Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run black (check only)
        run: black --check .

      - name: Run ruff (lint)
        run: ruff check .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings
