name: Production

on:
  push:
    branches:
      - main

env:
  VERCEL_PAT: ${{ secrets.VERCEL_PAT }}
  VERCEL_ORG_ID: ${{ vars.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

jobs:
  check-env-vars:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check env vars
        run: echo "Checking env vars..."

  deploy:
    runs-on: ubuntu-latest
    needs: check-env-vars
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Build with Vercel
        run: vercel build
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ env.VERCEL_PAT }} --scope=${{ env.VERCEL_ORG_ID }}
