name: Production

on:
  push:
    branches:
      - main

jobs:
  check-env-vars:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check VERCEL_PAT and VERCEL_PROJECT_NAME length
        run: |
          VERCEL_PAT_LEN=${#VERCEL_PAT}
          VERCEL_PROJECT_NAME_LEN=${#VERCEL_PROJECT_NAME}
          echo "VERCEL_PAT length: $VERCEL_PAT_LEN"
          echo "VERCEL_PROJECT_NAME length: $VERCEL_PROJECT_NAME_LEN"
        env:
          VERCEL_PAT: ${{ secrets.VERCEL_PAT }}
          VERCEL_PROJECT_NAME: ${{ vars.VERCEL_PROJECT_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: check-env-vars
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_PAT }} --confirm --scope ${{ vars.VERCEL_ORG_NAME }} --project ${{ vars.VERCEL_PROJECT_NAME }}
        env:
          VERCEL_PAT: ${{ secrets.VERCEL_PAT }}
          VERCEL_PROJECT_NAME: ${{ vars.VERCEL_PROJECT_NAME }}
          VERCEL_ORG_NAME: ${{ vars.VERCEL_ORG_NAME }}
