name: Production

on:
  push:
    branches:
      - main

env:
  VERCEL_PAT: ${{ secrets.VERCEL_PAT }}
  VERCEL_TEAM_ID: ${{ vars.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

jobs:
  check-env-vars:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check env vars
        run: echo "Checking env vars..."

  deploy:
    runs-on: ubuntu-latest
    needs: check-env-vars
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ env.VERCEL_PAT }} --org=${{ env.VERCEL_TEAM_ID }} --project=${{ env.VERCEL_PROJECT_ID }}
